### ISSUE TITLE
[test] slackへ通知を投げる

### ISSUE THREAD

**Issue by Yuto5176** [FunLocks/team2003#1]
discordで連絡してあまりslackを使っていないので、
生存確認のためにslackに通知を投げたい
通知設定はデフォルト
※issueにしたのはテストも兼ねて
参考
> https://qiita.com/unsoluble_sugar/items/e42ac352400598a24915

**Comment by Oxypetalum7** [comment]
botにslackへ自分の進捗投げたい場合は個人毎に設定が必要みたい
チャンネル欄→Apps右の＋ボタン→github
で適用されるはず
現在ゆうとと自分のみ適用済み？
