### ISSUE TITLE
キャラクターの解釈違いを無くす

### ISSUE THREAD

**Issue by Yuto5176** [FunLocks/team2003#16]
キャラクターの解釈を一致させて一貫性を保ちたい。
具体的な要素として語尾や性格などが考えられる。

**Comment by Oxypetalum7** [comment]
出典が江戸時代後期なので、古めかしい感じなイメージ。
語尾は「～じゃ！」

>Wikipediaより
>アマビエと名乗るものが出現し、役人に対して「当年より6ヶ年の間[注 2]は諸国で豊作がつづく。しかし同時に疫病が流行するから、私の姿を描き写した絵を人々に早々に見せよ。」

世話焼きなおばあちゃんみたいな？

**Comment by Yuto5176** [comment]
ok その線で
